### ISSUE TITLE
Live TV funktioniert nicht mehr

### ISSUE THREAD

**Issue by hrickes** [Maven85/plugin.video.7tv-webapi#2]
Hallo Zusammen,

mit folgender Änderung lässt sich das Problem beseitigen.

diff -urN plugin.video.7tv-webapi-master.orig/resources/lib/seventv.py plugin.video.7tv-webapi-master/resources/lib/seventv.py
--- plugin.video.7tv-webapi-master.orig/resources/lib/seventv.py        2018-07-05 16:31:28.000000000 +0200
+++ plugin.video.7tv-webapi-master/resources/lib/seventv.py     2019-02-17 19:52:36.977601613 +0100
@@ -137,6 +137,7 @@
     li = xbmcgui.ListItem(path=data['url'] + "|" + userAgent)
     li.setProperty("inputstream.adaptive.license_type", "com.widevine.alpha")
     li.setProperty("inputstream.adaptive.manifest_type", "mpd")
+    li.setProperty("inputstream.adaptive.manifest_update_parameter", "full")
     li.setProperty('inputstreamaddon', 'inputstream.adaptive')
 
     try:

**Comment by Maven85** [comment]
Vielen Dank, habe ich übernommen.

[Commit](https://github.com/Maven85/plugin.video.7tv-webapi/commit/3eb01b83abbeccc183488bbf8d38529687f7470b)
